In [2]:
pip install pandas pyarrow

Collecting pandas
  Using cached pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pyarrow
  Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Installing collected packages: pyarrow, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

dim_customers_df = pd.read_parquet("/tmp/test-data/output/gold/dim_customers/",engine="pyarrow")
dim_customers_df.head()

,customer_sk,customer_id,gender,province,income_band,segment,risk_score,kyc_status,age_band
0,1008800172827196581,00017a03-841a-0f03-0064-56a094f6855c,F,Eastern Cape,MIDDLE,PRIVATE,4,VERIFIED,36-45
1,675435330695848375,00019698-c421-eac3-3982-e54188216dd4,M,Gauteng,MIDDLE,PRIVATE,2,VERIFIED,36-45
2,125781383359498547,0001f3a8-478a-f6cc-618b-f63a87befae0,F,Gauteng,MIDDLE,EMERGING,6,VERIFIED,26-35
3,936330970694991524,0002a003-26da-f2f6-3563-e310060566fe,M,Gauteng,LOWER_MIDDLE,MASS,2,VERIFIED,36-45
4,519350510773953476,000382c2-1ecb-35d7-168a-7fe1892cba73,M,Gauteng,LOWER_MIDDLE,MASS,5,VERIFIED,46-55

In [5]:
dim_accounts_df = pd.read_parquet("/tmp/test-data/output/gold/dim_accounts/",engine="pyarrow")
dim_accounts_df.head()

,account_sk,account_id,customer_id,account_type,account_status,open_date,product_tier,digital_channel,credit_limit,current_balance,last_activity_date
0,465712839576187761,000121ad-d2fa-1922-5e73-800b58500587,3ab8bfcc-c74a-767a-25a3-1d346072d571,SAVINGS,ACTIVE,2022-01-06,STANDARD,APP,None,37306.18,2025-05-22
1,1057146682128198356,000135c5-f285-52d2-77e9-c4dd2f699e85,39c6e508-2edd-1df2-025e-2799b77343e8,TRANSACTIONAL,ACTIVE,2021-05-05,STANDARD,WEB,None,18988.63,2022-09-26
2,527861282859770625,00025b87-8096-23bf-3eb0-1cdbaf9cd3e1,493d0a3e-82c5-4ae1-4b39-761681faf601,SAVINGS,CLOSED,2025-06-10,PREMIUM,APP,None,39667.07,2025-11-19
3,372804130994145210,0002c114-c6ed-db4c-5763-5e1d3aba3798,3588fb7a-dcdb-08ef-1102-8e19aa910888,CREDIT,SUSPENDED,2025-05-17,BASIC,APP,75000.00,-16020.36,2025-07-24
4,1132971949088384527,0003e013-b16d-2e9e-49fc-be30f800bc61,40c917e2-1130-b494-17a9-36e617d53175,SAVINGS,ACTIVE,2018-05-12,STANDARD,APP,None,48581.69,2021-03-23